#!/usr/bin/env bash
# init-worktree-seat.sh — first-session initializer for a fresh claude-code worktree
#
# Wired as a SessionStart hook in the main repo's .claude/settings.json. Fires on
# every session start, but fast-paths out the moment `.beads/actor` already exists —
# so only the first session in a brand-new worktree pays any cost.
#
# On a fresh worktree (no `.beads/actor` yet), this script:
#   1. Verifies we are inside a git worktree (not the primary checkout) and the
#      working tree is clean.
#   2. `git fetch origin` (best-effort) + `git reset --hard origin/main`, so the
#      new worktree starts on current main instead of inheriting whatever stale
#      branch HEAD was picked at `git worktree add` time. This is the ghost-main
#      antidote — see hash-thing-uc4.
#   3. Picks the next free seat from the 5-seat auto-pool
#      (flint · cairn · onyx · ember · spark), scanning sibling worktrees'
#      `.beads/actor` files to find gaps.
#   4. Writes the chosen seat to `.beads/actor` and points `.beads/redirect`
#      at the shared main-repo tracker state.
#
# Design decisions (hash-thing-9uh, edward answered 2026-04-11):
#   - Mayor is NOT in the auto-pool. To seat a mayor, set `.beads/actor` manually
#     before the first session.
#   - If all 5 pool seats are in use, the script exits 1 with a clear message.
#     No silent fallback to numbered seats.
#   - Safety rails matter more than the "just type claude and go" promise:
#     a dirty working tree or a non-worktree checkout aborts the auto-reset.
#
# Exit 0 on success OR clean skip (already initialized, or safety rail tripped).
# Exit 1 ONLY when the user almost certainly wants to know (pool exhausted).

set -euo pipefail

repo_root_from_common_git() {
    git rev-parse --path-format=absolute --git-common-dir 2>/dev/null | sed 's|/\.git$||'
}

# --- Fast path: if seat file already exists, do nothing. ---------------------
# This is the hot path — fires on every SessionStart — and needs to stay cheap.
if [[ -f .beads/actor ]]; then
    exit 0
fi

# --- Safety rail 1: must be in a git worktree (not the primary checkout). ----
# A worktree's `.git` is a FILE containing `gitdir: ...`. The primary checkout's
# `.git` is a DIRECTORY. We never want to `git reset --hard` the primary.
if [[ ! -f .git ]]; then
    # Not a worktree. Silent skip — this hook fires in the primary too.
    exit 0
fi

# --- Safety rail 2: must be at the worktree root. ----------------------------
# The hook sets cwd to the session's starting dir, which should be the worktree
# root. If someone invokes claude from a subdir, bail so we don't walk up and
# clobber state.
WORKTREE_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || true)
if [[ -z "$WORKTREE_ROOT" || "$WORKTREE_ROOT" != "$PWD" ]]; then
    echo "init-worktree-seat: not at worktree root ($PWD vs $WORKTREE_ROOT), skipping" >&2
    exit 0
fi

# --- Safety rail 3: working tree must be clean. ------------------------------
# A fresh `git worktree add` produces a clean tree. If there are uncommitted
# changes, something is weird — we don't reset-hard over user work.
if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "init-worktree-seat: working tree dirty, skipping reset (leave .beads/actor manually)" >&2
    exit 0
fi

# --- Safety rail 4: branch must look fresh (generated by `git worktree add`). -
# `git worktree add` generates branch names like `worktree-<slug>`. If the
# branch already has a seat prefix (`flint/...`, `cairn/...`) or a non-default
# shape, a real agent has been here — don't clobber their work. This is the
# crucial guard for backfilling existing worktrees that happen to be missing
# `.beads/actor` for historical reasons.
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)
if [[ "$CURRENT_BRANCH" != worktree-* ]]; then
    echo "init-worktree-seat: branch '$CURRENT_BRANCH' looks agent-owned, skipping reset" >&2
    echo "init-worktree-seat:   (write .beads/actor manually if you want a seat)" >&2
    exit 0
fi

# --- Step 1: fetch + reset to origin/main. -----------------------------------
# `git fetch` is best-effort — offline work shouldn't fail the session start.
# `git reset --hard` happens regardless, against whatever origin/main we have
# locally; this is the ghost-main antidote.
git fetch origin 2>/dev/null || true
if git rev-parse --verify origin/main >/dev/null 2>&1; then
    git reset --hard origin/main >/dev/null 2>&1
else
    echo "init-worktree-seat: origin/main not found, skipping reset" >&2
fi

# --- Step 2: pick free seat from the 5-seat auto-pool. -----------------------
# Pool order is fixed and meaningful — first gap wins. Mayor is not in the pool.
POOL=(flint cairn onyx ember spark)

# Sibling worktrees live at ../<name>/.beads/actor relative to this worktree.
# The main repo's .claude/worktrees/ dir is the natural home for all of them.
WORKTREES_DIR=$(cd .. && pwd)

# Gather the set of seats currently in use by OTHER worktrees. This worktree is
# about to claim one, so we exclude ourselves (which has no actor file yet).
USED=""
for actor_file in "$WORKTREES_DIR"/*/.beads/actor; do
    if [[ -f "$actor_file" ]]; then
        USED="$USED $(cat "$actor_file" 2>/dev/null)"
    fi
done

# Walk the pool in order; first seat not in USED is ours.
for seat in "${POOL[@]}"; do
    if ! grep -qw "$seat" <<< "$USED"; then
        REPO_ROOT=$(repo_root_from_common_git)
        mkdir -p .beads
        chmod 700 .beads 2>/dev/null || true
        echo "$seat" > .beads/actor
        if [[ -n "$REPO_ROOT" && -d "$REPO_ROOT/.beads" ]]; then
            echo "$REPO_ROOT/.beads" > .beads/redirect
        fi
        echo "init-worktree-seat: assigned seat '$seat' (worktree=$(basename "$PWD"))"
        exit 0
    fi
done

# --- Pool exhausted. ---------------------------------------------------------
# This is a real "hey, look at this" condition — don't silently fall back to
# numbered seats, and don't let the session proceed without a known identity.
echo "init-worktree-seat: ERROR all 5 pool seats in use (${POOL[*]})" >&2
echo "init-worktree-seat:   either retire a worktree or assign .beads/actor manually" >&2
exit 1
